config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy'
  end

  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  rolify

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :recoverable,
         :omniauthable,
         :omniauth_providers => [:facebook, :twitter]

  # validations
  VALID_NICKNAME_REGEX = /\A[ㄱ-ㅎ가-힣a-z0-9_]+\z/i

  validates :nickname,
    presence: true,
    exclusion: { in: %w(app new edit index session login logout users admin all crew issue group project) },
    format: { with: VALID_NICKNAME_REGEX },
    uniqueness: { case_sensitive: false },
    length: { maximum: 20 }
  validate :nickname_exclude_pattern
  validates :email,
    presence: true,
    format: { with: Devise.email_regexp },
    uniqueness: {scope: [:provider]}
  validates :uid, uniqueness: {scope: [:provider]}
  validates :password,
    presence: true,
    confirmation: true,
    length: Devise.password_length,
    if: :password_required?

  validates_confirmation_of :password, if: :password_required?

  # filters
  before_save :downcase_nickname
  before_validation :strip_whitespace_nickname, only: :nickname
  before_save :set_uid

  # mount
  mount_uploader :image, ImageUploader

  # scope
  default_scope { order('id DESC') }
  scope :not_someone, ->(someone) { where.not(id: someone.id) }

  # methods for devises/auth
  def self.parse_omniauth(data)
    {provider: data['provider'], uid: data['uid'], email: data['info']['email'], image: data['info']['image']}
  end

  def self.new_with_session(params, session)
    resource = super
    auth = session["devise.omniauth_data"]
    if auth.present?
      auth["email"] = params['email'] if params['email'].present?
      resource.assign_attributes(auth)
      resource.password = Devise.friendly_token[0,20]
      resource.confirmed_at = DateTime.now
      resource.remote_image_url = auth['image']
    else
      resource.provider = 'email'
    end
    resource
  end

  def self.find_for_omniauth(auth)
    where(provider: auth[:provider], uid: auth[:uid]).first
  end

  # email auth

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    email = conditions.delete(:email)
    where(conditions.to_h).where(["provider = 'email' AND uid = :value", { :value => email.downcase }]).first
  end

  # for recovering the password for an account
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    unless conditions.has_key?(:confirmation_token)
      conditions.merge! provider: 'email'
    end
    where(conditions.to_h).first
  end

  private

  def set_uid
    self.uid = self.email if self.provider == 'email'
  end

  def downcase_nickname
    self.nickname = nickname.downcase
  end

  def nickname_exclude_pattern
    if (self.nickname =~ /\Aparti.*\z/i) and (self.nickname_was !~ /\Aparti.*\z/i)
      errors.add(:nickname, I18n.t('errors.messages.taken'))
    end
  end

  def strip_whitespace_nickname
    self.nickname = self.nickname.strip unless self.nickname.nil?
  end

  def password_required?
    !persisted? || !password.nil? || !password_confirmation.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  layout :layout_by_resource, if: :devise_controller?

  private

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  prepend_before_filter :require_no_authentication, only: [:facebook, :twitter, :naver]

  def facebook
    run_omniauth
  end

  def twitter
    run_omniauth
  end

  def failure
    logger.fatal "Omniauth Fail : kind: #{OmniAuth::Utils.camelize(failed_strategy.try(:name))}, reason: #{failure_message}"
    logger.fatal "Omniauth Env : #{request.env.inspect}"
    redirect_to root_path
  end

  private

  def run_omniauth
    parsed_data = User.parse_omniauth(request.env["omniauth.auth"])
    remember_me = request.env["omniauth.params"].try(:fetch, "remember_me", false)
    parsed_data[:remember_me] = remember_me
    @user = User.find_for_omniauth(parsed_data)
    if @user.present?
      @user.remember_me = remember_me
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => @user.provider) if is_navigational_format?
    else
      session["devise.omniauth_data"] = parsed_data
      session["omniauth.params_data"] = request.env["omniauth.params"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  skip_before_filter :verify_authenticity_token, :only => :create

  # Overwrite update_resource to let users to update their user without giving their password
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  private

  def sign_up_params
    params.require(:user).permit(:remember_me, :nickname, :image, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:remember_me, :nickname, :description, :image, :email, :enable_mailing)
  end

  def after_inactive_sign_up_path_for(resource)
    root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.haml
#site-header
  %nav.navbar.navbar-inverse.navbar-fixed-top
    .container
      .navbar-header
        %button.navbar-toggle.collapsed{"data-target": "#collapsable", "data-toggle": "collapse", type: "button"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{ href: root_path }
          피플

      #collapsable.collapse.navbar-collapse
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li
              = link_to "#{current_user.nickname} 프로필", edit_user_registration_path, class: 'item'
            %li
              = link_to '로그아웃', sign_out_path, method: :delete, class: 'item'
          - else
            %li
              = link_to new_user_session_path, class: 'item' do
                로그인 &middot; 가입

app/views/layouts/application.html.haml
!!!
%html{:lang => I18n.locale}
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no", :name => "viewport"}

    %title 피플

    = stylesheet_link_tag 'application', media: 'all'
    %link{href: "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", rel: "stylesheet"}

    /[if lt IE 9]
    %script{:src => "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"}
    %script{:src => "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"}

    = csrf_meta_tags

  %body{class: "app-#{params[:controller]} app-#{params[:controller]}-#{params[:action]}"}
    %section(style='position: fixed; z-index: 1000; width: 100%')
      .container
        .unobtrusive-flash-container

    = render 'application/header'
    = yield

    = javascript_include_tag 'application'
    = yield :script if content_for?(:script)

app/views/layouts/devise.html.haml
%section
  .container{ style: 'margin-top: 100px' }
    = render file: 'layouts/application'

app/views/pages/home.html.haml
.jumbotron
  .container
    %h1 피플